TWEAK_NAME = LocusPrefs

$(TWEAK_NAME)_FILES =  $(wildcard *.m)
$(TWEAK_NAME)_PRIVATE_FRAMEWORKS = Preferences
$(TWEAK_NAME)_CFLAGS = -fobjc-arc


include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk